~~~
Author: Sangin Kim
Date  : 6 August 2023
~~~
> ### Input: 6, 6
> ### Output:
>    |  0 |  1 |  2 |  3 |  4 |  5 |
>    |----|----|----|----|----|----|
>    | 19 | 20 | 21 | 22 | 23 |  6 |
>    | 18 | 31 | 32 | 33 | 24 |  7 |
>    | 17 | 30 | 35 | 34 | 25 |  8 |
>    | 16 | 29 | 28 | 27 | 26 |  9 |
>    | 15 | 14 | 13 | 12 | 11 | 10 |
> ### 위처럼 6, 6이라는 입력을 주면 6X6 매트릭스에 나선형 회전을 한 값을 출력해야 한다.
> ### 이를 가능케하는 함수를 만들어라.

----

# 1. Analysis

## Case 1)
> #### Input: 6, 6
> #### Output:
>    |  0 |  1 |  2 |  3 |  4 |  5 |
>    |----|----|----|----|----|----|
>    | 19 | 20 | 21 | 22 | 23 |  6 |
>    | 18 | 31 | 32 | 33 | 24 |  7 |
>    | 17 | 30 | 35 | 34 | 25 |  8 |
>    | 16 | 29 | 28 | 27 | 26 |  9 |
>    | 15 | 14 | 13 | 12 | 11 | 10 |

### Analyze pattern
~~~
Stage 1: 5 ( 0, 1, 2, 3, 4) - 5 ( 5, 6, 7, 8, 9) - 5 (10,11,12,13,14) -
Stage 2: 4 (15,16,17,18) ---- 4 (19,20,21,22) ----
Stage 3: 3 (23,24,25) ------- 3 (26,27,28) -------
Stage 4: 2 (29,30) ---------- 2 (31,32) ----------
Stage 5: 1 (33) ------------- 1 (34) -------------
Stage 6: 1 (35)
~~~

## Case 2)
> #### Input: 8, 8
> #### Output:
>   |  0 |  1 |  2 |  3 |  4 |  5 |  6 |  7 |
>   |----|----|----|----|----|----|----|----|
>   | 27 | 28 | 29 | 30 | 31 | 32 | 33 |  8 | 
>   | 26 | 47 | 48 | 49 | 50 | 51 | 34 |  9 |
>   | 25 | 46 | 59 | 60 | 61 | 52 | 35 | 10 |
>   | 24 | 45 | 58 | 63 | 62 | 53 | 36 | 11 |
>   | 23 | 44 | 57 | 56 | 55 | 54 | 37 | 12 |
>   | 22 | 43 | 42 | 41 | 40 | 39 | 38 | 13 |
>   | 21 | 20 | 19 | 18 | 17 | 16 | 15 | 14 |

### Analyze pattern
~~~
Stage 1: 7 ( 0, 1, 2, 3, 4, 5, 6) - 7 ( 7, 8, 9,10,11,12,13) - 7 (14,15,16,17,18,19,20) -
Stage 2: 6 (21,22,23,24,25,26) ---- 6 (27,28,29,30,31,32) ---- 
Stage 3: 5 (33,34,35,36,37) ------- 5 (38,39,40,41,42) -------
Stage 4: 4 (43,44,45,46) ---------- 4 (47,48,49,50) ----------
Stage 5: 3 (51,52,53) ------------- 3 (54,55,56) -------------
Stage 6: 2 (57,58) ---------------- 2 (59,60) ----------------
Stage 7: 1 (61) ------------------- 1 (62) -------------------
Stage 8: 1 (63)
~~~

> ### Intruducing long/short index
> #### `l`: long index / `s`: short index 
> #### `l` = `s` = 8 - 1 = 7 
> ~~~
> l7 - s7 - l7 - => l-=1; s-=1
> s6 - l6 ------ => l-=1; s-=1
> s5 - l5 ------ => l-=1; s-=1
> s4 - l4 ------ => l-=1; s-=1
> s3 - l3 ------ => l-=1; s-=1
> s2 - l2 ------ => l-=1; s-=1
> s1 - l1 ------ => l-=1; s-=1
> s0 (replace with 1) (end point)
> ~~~

## Case 3)
> #### Input: 4, 4
> #### Output:
>  |  0 |  1 |  2 |  3 |
>  |----|----|----|----|
>  | 11 | 12 | 13 |  4 |
>  | 10 | 15 | 14 |  5 |
>  |  9 |  8 |  7 |  6 |

### Analyze pattern
~~~
Stage 1: 3 ( 0, 1, 2) - 3 ( 3, 4, 5) - 3 ( 6, 7, 8) -
Stage 2: 2 ( 9,10) ---- 2 (11,12) ---- 
Stage 3: 1 (13) ------- 1 (14) ------- 
Stage 4: 1 (15)
~~~

> #### `l=s=4-1`
> ~~~
> l3 - s3 - l3 - => l-=1; s-=1
> s2 - l2 ------ => l-=1; s-=1
> s1 - l1 ------ => l-=1; s-=1
> s0 (replace with 1) (end point)
> ~~~

## Case 4)
> #### Input: 3, 4
> #### Output:
>  |  0 |  1 |  2 |  3 |
>  |----|----|----|----|
>  |  9 | 10 | 11 |  4 |
>  |  8 |  7 |  6 |  5 |

### Analyze pattern
~~~
Stage 1:  3 ( 0, 1, 2) - 2 ( 3, 4) - 3 ( 5, 6, 7) -
Stage 2:  1 ( 8) ------- 2 ( 9,10) -
Stage 3:  1 (11)
~~~

> #### `l=4-1; s=3-1`
> ~~~
> l3 - s2 - l3 - => l-=1; s-=1
> s1 - l2 ------ => l-=1; s-=1
> s0 (replace with 1) (end point)
> ~~~

## Case 5)
> #### Input: 5, 4
> #### Output:
>   |  0 |  1 |  2 |  3 |
>   |----|----|----|----|
>   | 13 | 14 | 15 |  4 |
>   | 12 | 19 | 16 |  5 |
>   | 11 | 18 | 17 |  6 |
>   | 10 |  9 |  8 |  7 |

### Analyze pattern
~~~
Stage 1: 3 ( 0, 1, 2) - 4 ( 3, 4, 5, 6) - 3 ( 7, 8, 9) -
Stage 2: 3 (10,11,12) - 2 (13,14) -------
Stage 3: 2 (15,16) ---- 1 (17) ----------
Stage 4: 1 (18) ------- 1 (19)
~~~

> `l=5-1, s=4-1`
> ~~~
> s3 - l4 - s3 - (3 times) => l-=1; s-=1
> l3 - s2 ------ (2 times) => l-=1; s-=1
> l2 - s1 ------ (2 times) => l-=1; s-=1
> l1 - s0 (replace with 1) (end point)`
> ~~~

# [ Conclusion ]
* Pattern found: 
  - 조각(segment)의 길이는 일반적으로 l, s 두가지로 정의될 수 있다.
     - l == s (square)
     - l != s (rectangle)
  - 조각은 ...-l-s-l-s-l-... 순으로 번갈아가며 나아간다.
  - 반복횟수는 3 -> 2 -> 2 -> ... -> 2 -> (1) 순서로 줄어든다. 
  - 다음 반복횟수로 넘어갈 때마다 l-=1; s-=1 을 취한다.
  - l 혹은 s 둘중 하나라도 0이 될때를 end point로 정의하며, 그 때는 그 0을 1로 치환후 끝낸다.
  - 시작 조각이 l인지 s인지는 회전방향과 초기위치로 결정된다.

----

# 2. Define `class`: `seg_path`

매번 클래스 연습해야지 해야지 하다가 드디어 고생 끝에 시도해봤습니다.

In [13]:
class seg_path:
    def __init__(self, init_idx, sprial):
        self.r_pos = init_idx[0]
        self.c_pos = init_idx[1]
        self.sprial = sprial
        self.get_dir()
    
    def sym_turn(self):
        seg_lst = ["r","c"]
        seg_lst.remove(self.sym)
        self.sym = seg_lst[0]
    
    def dir_turn(self):
        self.dir_cmpl = self.dir_cmpl * 1j
        self.dir = (self.dir_cmpl).real

    def get_dir(self):
        # get back init_idx
        idcs = [self.r_pos, self.c_pos]

        # check which edge 'init_idx' locates
        # [True, True]  : "ul"
        # [True, False] : "ur"
        # [False, True] : "bl"
        # [False, False]: "br"
        check_idx = list(map(lambda x, y: x==y, idcs, [0,0]))

        # Assume sprial=="clock"
        # Complex directions (pattern found empirically)
        """
 - clock-wise ("clock")
 |        (+1)
 |         -->
 |      ^        |  (+1)
 | (-1) |        v
 |         <--
 |         (-1)
 |
 |- init_pos (init_idx)
 |    |- "ul" ([0,0]): init_dir_cmpl = +1 (-> +1)  >>  1-1j
 |    |- "ur" ([0,c]): init_dir_cmpl = +1 (-> -1)  >>  1+1j
 |    |- "bl" ([r,0]): init_dir_cmpl = -1 (-> +1)  >> -1-1j
 |    |- "br" ([r,c]): init_dir_cmpl = -1 (-> -1)  >> -1+1j
 |
 |- init_dir = init_dir_cmpl.real()
 |
 - Anti clock-wise ("anti")
 |        (-1)
 |         <--
 | (+1) |        ^
 |      v        |  (-1)
 |         -->
 |         (+1)
 |- init_pos
 |    |- "ul" ([0,0]): init_dir_cmpl = +1 (-> +1)  >>  1-1j
 |    |- "ur" ([0,c]): init_dir_cmpl = -1 (-> +1)  >> -1-1j
 |    |- "bl" ([r,0]): init_dir_cmpl = +1 (-> -1)  >>  1+1j
 |    |- "br" ([r,c]): init_dir_cmpl = -1 (-> -1)  >> -1+1j
 |
 |- init_dir = init_dir_cmpl.real()
 |
 - "clock" <-> "anti" : conversion by "init_dir.conjugate()*-1*1j"
        """
        if   check_idx == [True, True]:
            self.dir_cmpl =  1-1j
            self.sym = "c"
        elif check_idx == [True, False]:
            self.dir_cmpl =  1+1j
            self.sym = "r"
        elif check_idx == [False, True]:
            self.dir_cmpl = -1-1j
            self.sym = "r"
        elif check_idx == [False, False]:
            self.dir_cmpl = -1+1j
            self.sym = "c"
        
        # check 'sprial'
        if self.sprial == "clock":
            pass
        elif self.sprial == "anti":
            self.dir_cmpl = self.dir_cmpl.conjugate()*(-1)*(1j) # emprical law
            self.sym_turn()
        else:
            raise ValueError("Wrong 'sprial'. Choose one of 'clock' or 'anti'.")
        
        # Also store real direction
        self.dir = (self.dir_cmpl).real
        
    def get_path(self, syms):
        r = syms["r"]
        c = syms["c"]

        if   self.sym == "c":
            if   self.dir ==  1:
                path = (self.r_pos, range(self.c_pos,self.c_pos+c))
                self.c_pos += c # Update c_pos
            elif self.dir == -1:
                path = (self.r_pos, range(self.c_pos, self.c_pos-c, -1))
                self.c_pos -= c # Update c_pos

        elif self.sym == "r":
            if   self.dir ==  1:
                path = (range(self.r_pos,self.r_pos+r), self.c_pos)
                self.r_pos += r # Update r_pos
            elif self.dir == -1:
                path = (range(self.r_pos, self.r_pos-r, -1), self.c_pos)
                self.r_pos -= r # Update r_pos
        
        self.path = path
        
        # For next turn
        self.sym_turn()
        self.dir_turn()

In [14]:
def get_init_pos_tup(input_dim):
    """
 - Initial position:
    |- r = input_dim[0] - 1
    |- c = input_dim[1] - 1 
    |============================|
    | edge               | index |
    |--------------------|-------|
    | "ul": upper-left   | [0,0] |
    | "ur": upper-right  | [0,c] |
    | "bl": bottom-left  | [r,0] |
    | "br": bottom-right | [r,c] |
    |============================|
    """
    init_pos_tup = dict(ul = [0,0], 
                        ur = [0,input_dim[1]-1], 
                        bl = [input_dim[0]-1,0], 
                        br = [input_dim[0]-1, input_dim[1]-1])
    return(init_pos_tup)

# 3. Define `main` function

In [15]:
def main(input_dim, input_pos, input_dir, verbose=True):
    import numpy as np
    """
     - Grid dimension: 2D with any number
        e.g.) [5,5] , [6,6] , [3,4]

     - Initial position: "ul", "ur", "bl", "br"
        c.f.)
        |- r = input_dim[0] - 1
        |- c = input_dim[1] - 1 
        |============================|
        | edge               | index |
        |--------------------|-------|
        | "ul": upper-left   | [0,0] |
        | "ur": upper-right  | [0,c] |
        | "bl": bottom-left  | [r,0] |
        | "br": bottom-right | [r,c] |
        |============================|

    - Sprial directions: "clock", "anti"
         2 Possible direction: clock-wise (clock), anticlock-wise (anti)
    
    """

    # Initialize grid with zeros
    grid = np.zeros(input_dim)
    
    # Length of rows and columns
    row_len = input_dim[0]
    col_len = input_dim[1]
    
    # Generate straight sequence with respect to the given dimension.
    # e.g.)
    #   6 x 6 = 36 -> [ 0, 1, 2, ..., 34, 35]
    #   3 x 4 = 12 -> [ 0, 1, 2, ..., 10, 11]
    straight_seq = np.array(range(row_len * col_len))
    init_pos_tup = get_init_pos_tup(input_dim)
    init_idx = init_pos_tup[input_pos]
    
    # Initialize 
    r, c = row_len-1, col_len-1 # row index, column index
    straight_seq_copy = straight_seq.copy()
    
    # Start
    seg = seg_path(init_idx, input_dir)

    # Stage iteration
    stage_num = 0
    while True:
        # Stage number
        stage_num += 1

        # Printing
        if verbose:
            print("|> Stage "+str(stage_num))

        # Step number
        if stage_num == 1:
            step_num = 3
        else:
            step_num = 2

        # Step iteration
        for step in range(step_num):
            # End point
            if   r == 0 and c == 0:
                r = 1
                c = 1
            elif r == 0:
                r = 1
            elif c == 0:
                c = 1
            else:
                pass

            # Printing
            if verbose:
                print("|-> Step "+str(step+1))

            # Get segment index
            idx_dir = range(0,eval(seg.sym))

            # Get segment values from sequence
            seg_vals = straight_seq_copy[idx_dir]

            # Get path to insert segment values
            syms = {"r":r, "c":c}
            seg.get_path(syms)

            # Insert segment values into the path
            grid[seg.path] = seg_vals

            # Delete used segment from original sequence
            straight_seq_copy = np.delete(straight_seq_copy, idx_dir)

            # Printing
            if verbose:
                print(grid)

            # Break for loop
            if len(straight_seq_copy) == 0:
                break
        
        # Break while loop
        if len(straight_seq_copy) == 0:
            break
        
        # Decrease r & c
        r-=1; c-=1
    
    if verbose:
        print("|> Filling Spiral Array Done!")

    return(grid)

---

# 4. Result
> ~~~
>   "ul", "ur", "bl", "br" (4) 
>              X 
>       "clock", "anti" (2) 
>              || 
>         Total 8 cases 
> with arbitrary input dimension
> ~~~

In [16]:
result1 = main([4,4], "ul", "clock")

|> Stage 1
|-> Step 1
[[0. 1. 2. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
|-> Step 2
[[0. 1. 2. 3.]
 [0. 0. 0. 4.]
 [0. 0. 0. 5.]
 [0. 0. 0. 0.]]
|-> Step 3
[[0. 1. 2. 3.]
 [0. 0. 0. 4.]
 [0. 0. 0. 5.]
 [0. 8. 7. 6.]]
|> Stage 2
|-> Step 1
[[ 0.  1.  2.  3.]
 [ 0.  0.  0.  4.]
 [10.  0.  0.  5.]
 [ 9.  8.  7.  6.]]
|-> Step 2
[[ 0.  1.  2.  3.]
 [11. 12.  0.  4.]
 [10.  0.  0.  5.]
 [ 9.  8.  7.  6.]]
|> Stage 3
|-> Step 1
[[ 0.  1.  2.  3.]
 [11. 12. 13.  4.]
 [10.  0.  0.  5.]
 [ 9.  8.  7.  6.]]
|-> Step 2
[[ 0.  1.  2.  3.]
 [11. 12. 13.  4.]
 [10.  0. 14.  5.]
 [ 9.  8.  7.  6.]]
|> Stage 4
|-> Step 1
[[ 0.  1.  2.  3.]
 [11. 12. 13.  4.]
 [10. 15. 14.  5.]
 [ 9.  8.  7.  6.]]
|> Filling Spiral Array Done!


In [17]:
result2 = main([6,5], "ul", "anti")

|> Stage 1
|-> Step 1
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
|-> Step 2
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]
 [5. 6. 7. 8. 0.]]
|-> Step 3
[[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0. 13.]
 [ 2.  0.  0.  0. 12.]
 [ 3.  0.  0.  0. 11.]
 [ 4.  0.  0.  0. 10.]
 [ 5.  6.  7.  8.  9.]]
|> Stage 2
|-> Step 1
[[ 0.  0. 16. 15. 14.]
 [ 1.  0.  0.  0. 13.]
 [ 2.  0.  0.  0. 12.]
 [ 3.  0.  0.  0. 11.]
 [ 4.  0.  0.  0. 10.]
 [ 5.  6.  7.  8.  9.]]
|-> Step 2
[[ 0. 17. 16. 15. 14.]
 [ 1. 18.  0.  0. 13.]
 [ 2. 19.  0.  0. 12.]
 [ 3. 20.  0.  0. 11.]
 [ 4.  0.  0.  0. 10.]
 [ 5.  6.  7.  8.  9.]]
|> Stage 3
|-> Step 1
[[ 0. 17. 16. 15. 14.]
 [ 1. 18.  0.  0. 13.]
 [ 2. 19.  0.  0. 12.]
 [ 3. 20.  0.  0. 11.]
 [ 4. 21. 22.  0. 10.]
 [ 5.  6.  7.  8.  9.]]
|-> Step 2
[[ 0. 17. 16. 15. 14.]
 [ 1. 18.  0.  0. 13.]
 [ 2. 19.  0. 25. 12.]
 [ 3. 20.  0. 24. 11.]
 [ 4. 21. 22. 23. 10.]
 

In [18]:
result3 = main([5,5], "ur", "clock")

|> Stage 1
|-> Step 1
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0.]]
|-> Step 2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 3.]
 [0. 7. 6. 5. 4.]]
|-> Step 3
[[ 0.  0.  0.  0.  0.]
 [11.  0.  0.  0.  1.]
 [10.  0.  0.  0.  2.]
 [ 9.  0.  0.  0.  3.]
 [ 8.  7.  6.  5.  4.]]
|> Stage 2
|-> Step 1
[[12. 13. 14.  0.  0.]
 [11.  0.  0.  0.  1.]
 [10.  0.  0.  0.  2.]
 [ 9.  0.  0.  0.  3.]
 [ 8.  7.  6.  5.  4.]]
|-> Step 2
[[12. 13. 14. 15.  0.]
 [11.  0.  0. 16.  1.]
 [10.  0.  0. 17.  2.]
 [ 9.  0.  0.  0.  3.]
 [ 8.  7.  6.  5.  4.]]
|> Stage 3
|-> Step 1
[[12. 13. 14. 15.  0.]
 [11.  0.  0. 16.  1.]
 [10.  0.  0. 17.  2.]
 [ 9.  0. 19. 18.  3.]
 [ 8.  7.  6.  5.  4.]]
|-> Step 2
[[12. 13. 14. 15.  0.]
 [11.  0.  0. 16.  1.]
 [10. 21.  0. 17.  2.]
 [ 9. 20. 19. 18.  3.]
 [ 8.  7.  6.  5.  4.]]
|> Stage 4
|-> Step 1
[[12. 13. 14. 15.  0.]
 [11. 22.  0. 16.  1.]
 [10. 21.  0. 17.  2.]
 [ 9. 20. 19. 18.  3.]
 [ 8.  7.  6. 

In [19]:
result4 = main([5,5], "ur", "anti")

|> Stage 1
|-> Step 1
[[0. 3. 2. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
|-> Step 2
[[4. 3. 2. 1. 0.]
 [5. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0.]
 [7. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
|-> Step 3
[[ 4.  3.  2.  1.  0.]
 [ 5.  0.  0.  0.  0.]
 [ 6.  0.  0.  0.  0.]
 [ 7.  0.  0.  0.  0.]
 [ 8.  9. 10. 11.  0.]]
|> Stage 2
|-> Step 1
[[ 4.  3.  2.  1.  0.]
 [ 5.  0.  0.  0.  0.]
 [ 6.  0.  0.  0. 14.]
 [ 7.  0.  0.  0. 13.]
 [ 8.  9. 10. 11. 12.]]
|-> Step 2
[[ 4.  3.  2.  1.  0.]
 [ 5.  0. 17. 16. 15.]
 [ 6.  0.  0.  0. 14.]
 [ 7.  0.  0.  0. 13.]
 [ 8.  9. 10. 11. 12.]]
|> Stage 3
|-> Step 1
[[ 4.  3.  2.  1.  0.]
 [ 5. 18. 17. 16. 15.]
 [ 6. 19.  0.  0. 14.]
 [ 7.  0.  0.  0. 13.]
 [ 8.  9. 10. 11. 12.]]
|-> Step 2
[[ 4.  3.  2.  1.  0.]
 [ 5. 18. 17. 16. 15.]
 [ 6. 19.  0.  0. 14.]
 [ 7. 20. 21.  0. 13.]
 [ 8.  9. 10. 11. 12.]]
|> Stage 4
|-> Step 1
[[ 4.  3.  2.  1.  0.]
 [ 5. 18. 17. 16. 15.]
 [ 6. 19.  0.  0. 14.]
 [ 7. 20. 21. 22. 13.]
 [ 8.  9. 10. 

In [20]:
result5 = main([7,4], "bl", "clock")

|> Stage 1
|-> Step 1
[[0. 0. 0. 0.]
 [5. 0. 0. 0.]
 [4. 0. 0. 0.]
 [3. 0. 0. 0.]
 [2. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
|-> Step 2
[[6. 7. 8. 0.]
 [5. 0. 0. 0.]
 [4. 0. 0. 0.]
 [3. 0. 0. 0.]
 [2. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
|-> Step 3
[[ 6.  7.  8.  9.]
 [ 5.  0.  0. 10.]
 [ 4.  0.  0. 11.]
 [ 3.  0.  0. 12.]
 [ 2.  0.  0. 13.]
 [ 1.  0.  0. 14.]
 [ 0.  0.  0.  0.]]
|> Stage 2
|-> Step 1
[[ 6.  7.  8.  9.]
 [ 5.  0.  0. 10.]
 [ 4.  0.  0. 11.]
 [ 3.  0.  0. 12.]
 [ 2.  0.  0. 13.]
 [ 1.  0.  0. 14.]
 [ 0.  0. 16. 15.]]
|-> Step 2
[[ 6.  7.  8.  9.]
 [ 5.  0.  0. 10.]
 [ 4. 21.  0. 11.]
 [ 3. 20.  0. 12.]
 [ 2. 19.  0. 13.]
 [ 1. 18.  0. 14.]
 [ 0. 17. 16. 15.]]
|> Stage 3
|-> Step 1
[[ 6.  7.  8.  9.]
 [ 5. 22.  0. 10.]
 [ 4. 21.  0. 11.]
 [ 3. 20.  0. 12.]
 [ 2. 19.  0. 13.]
 [ 1. 18.  0. 14.]
 [ 0. 17. 16. 15.]]
|-> Step 2
[[ 6.  7.  8.  9.]
 [ 5. 22. 23. 10.]
 [ 4. 21. 24. 11.]
 [ 3. 20. 25. 12.]
 [ 2. 19. 26. 13.]
 [ 1. 18.  0. 14.]
 [ 0. 17. 16. 15.]]
|> Stage

In [21]:
result6 = main([5,7], "bl", "anti")

|> Stage 1
|-> Step 1
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4. 5. 0.]]
|-> Step 2
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9.]
 [0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 0. 0. 0. 0. 7.]
 [0. 1. 2. 3. 4. 5. 6.]]
|-> Step 3
[[ 0. 15. 14. 13. 12. 11. 10.]
 [ 0.  0.  0.  0.  0.  0.  9.]
 [ 0.  0.  0.  0.  0.  0.  8.]
 [ 0.  0.  0.  0.  0.  0.  7.]
 [ 0.  1.  2.  3.  4.  5.  6.]]
|> Stage 2
|-> Step 1
[[16. 15. 14. 13. 12. 11. 10.]
 [17.  0.  0.  0.  0.  0.  9.]
 [18.  0.  0.  0.  0.  0.  8.]
 [ 0.  0.  0.  0.  0.  0.  7.]
 [ 0.  1.  2.  3.  4.  5.  6.]]
|-> Step 2
[[16. 15. 14. 13. 12. 11. 10.]
 [17.  0.  0.  0.  0.  0.  9.]
 [18.  0.  0.  0.  0.  0.  8.]
 [19. 20. 21. 22. 23.  0.  7.]
 [ 0.  1.  2.  3.  4.  5.  6.]]
|> Stage 3
|-> Step 1
[[16. 15. 14. 13. 12. 11. 10.]
 [17.  0.  0.  0.  0.  0.  9.]
 [18.  0.  0.  0.  0. 25.  8.]
 [19. 20. 21. 22. 23. 24.  7.]
 [ 0.  1.  2.  3.  4.  5.  6.]]
|-> Step 2
[[16. 15. 14. 13. 12. 11

In [22]:
result7 = main([6,5], "br", "clock")

|> Stage 1
|-> Step 1
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 3. 2. 1. 0.]]
|-> Step 2
[[0. 0. 0. 0. 0.]
 [8. 0. 0. 0. 0.]
 [7. 0. 0. 0. 0.]
 [6. 0. 0. 0. 0.]
 [5. 0. 0. 0. 0.]
 [4. 3. 2. 1. 0.]]
|-> Step 3
[[ 9. 10. 11. 12.  0.]
 [ 8.  0.  0.  0.  0.]
 [ 7.  0.  0.  0.  0.]
 [ 6.  0.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.]
 [ 4.  3.  2.  1.  0.]]
|> Stage 2
|-> Step 1
[[ 9. 10. 11. 12. 13.]
 [ 8.  0.  0.  0. 14.]
 [ 7.  0.  0.  0. 15.]
 [ 6.  0.  0.  0. 16.]
 [ 5.  0.  0.  0.  0.]
 [ 4.  3.  2.  1.  0.]]
|-> Step 2
[[ 9. 10. 11. 12. 13.]
 [ 8.  0.  0.  0. 14.]
 [ 7.  0.  0.  0. 15.]
 [ 6.  0.  0.  0. 16.]
 [ 5.  0. 19. 18. 17.]
 [ 4.  3.  2.  1.  0.]]
|> Stage 3
|-> Step 1
[[ 9. 10. 11. 12. 13.]
 [ 8.  0.  0.  0. 14.]
 [ 7. 22.  0.  0. 15.]
 [ 6. 21.  0.  0. 16.]
 [ 5. 20. 19. 18. 17.]
 [ 4.  3.  2.  1.  0.]]
|-> Step 2
[[ 9. 10. 11. 12. 13.]
 [ 8. 23. 24.  0. 14.]
 [ 7. 22.  0.  0. 15.]
 [ 6. 21.  0.  0. 16.]
 [ 5. 20. 19. 18. 17.]
 

In [23]:
result8 = main([3,9], "br", "anti")

|> Stage 1
|-> Step 1
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
|-> Step 2
[[0. 9. 8. 7. 6. 5. 4. 3. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
|-> Step 3
[[10.  9.  8.  7.  6.  5.  4.  3.  2.]
 [11.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]
|> Stage 2
|-> Step 1
[[10.  9.  8.  7.  6.  5.  4.  3.  2.]
 [11.  0.  0.  0.  0.  0.  0.  0.  1.]
 [12. 13. 14. 15. 16. 17. 18.  0.  0.]]
|-> Step 2
[[10.  9.  8.  7.  6.  5.  4.  3.  2.]
 [11.  0.  0.  0.  0.  0.  0.  0.  1.]
 [12. 13. 14. 15. 16. 17. 18. 19.  0.]]
|> Stage 3
|-> Step 1
[[10.  9.  8.  7.  6.  5.  4.  3.  2.]
 [11.  0. 25. 24. 23. 22. 21. 20.  1.]
 [12. 13. 14. 15. 16. 17. 18. 19.  0.]]
|-> Step 2
[[10.  9.  8.  7.  6.  5.  4.  3.  2.]
 [11. 26. 25. 24. 23. 22. 21. 20.  1.]
 [12. 13. 14. 15. 16. 17. 18. 19.  0.]]
|> Filling Spiral Array Done!


In [24]:
result9 = main([10,10], "br", "anti")

|> Stage 1
|-> Step 1
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 7.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 6.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
|-> Step 2
[[ 0. 17. 16. 15. 14. 13. 12. 11. 10.  9.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  8.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  7.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  6.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  5.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  4.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  3.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  2.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
|-> Step 3
[[18. 17. 16. 15. 14. 13. 12. 11. 10.  9.]
 [19.  0.  0.  0.  0.  0.  0.  0.  0.  8.]
 [20.  0.  0.  0.  0.  0.  0.  0.  0.  7.]
 [21.  0.  0.  0.  0.  0.  0.  0.  0.  6.]
 [22.  0.  0.  0.  0. 